fn main() {
    let gc = std::env::var("PILLOW_GC").unwrap_or_else(|_| default_gc());
    let alloc = std::env::var("PILLOW_ALLOC").unwrap_or_else(|_| default_alloc());

    match (gc.as_str(), alloc.as_str()) {
        ("marksweep", "bump") => {}
        ("rc", "native") => {}
        ("rc", "bump") => {}
        _ => panic!(
            "Invalid GC/Allocator combination: gc={gc} alloc={alloc}\n\
             Valid combinations:\n\
             - marksweep + bump\n\
             - rc + native\n\
             - rc + bump"
        ),
    }

    println!("cargo:rustc-cfg=pillow_gc=\"{gc}\"");
    println!("cargo:rustc-cfg=pillow_alloc=\"{alloc}\"");

    // Re-run if these change
    println!("cargo:rerun-if-env-changed=PILLOW_GC");
    println!("cargo:rerun-if-env-changed=PILLOW_ALLOC");
    println!("cargo:rerun-if-env-changed=PILLOW_BYTECODE");

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let bytecode_path = std::env::var("PILLOW_BYTECODE").unwrap_or_default();

    if !bytecode_path.is_empty() {
        let generated = format!(
            "// Generated by `build.rs`. Do not change!\npub const BYTECODE: &[u8] = include_bytes!({:?});",
            bytecode_path
        );
        std::fs::write(
            std::path::Path::new(&out_dir).join("bytecode.rs"),
            generated,
        )
        .unwrap();
        println!("cargo:rerun-if-changed={bytecode_path}");
    } else if !cfg!(feature = "std") {
        panic!("PILLOW_BYTECODE must be set in no_std builds");
    }
}

fn default_gc() -> String {
    if cfg!(feature = "std") {
        "rc".into()
    } else {
        "marksweep".into()
    }
}

fn default_alloc() -> String {
    if cfg!(feature = "std") {
        "native".into()
    } else {
        "bump".into()
    }
}
